name: test and build gem
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: test + build
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Set up ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
      
    - name: rspec
      run: |
        gem install bundler --no-doc
        bundle install
        bundle exec rspec
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2
    
    - name: build gem
      run: |
        gem build cfhighlander.gemspec