name: release gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish gem
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Set up ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{secrets.RUBYGEMS_API_KEY}}