name: release docker image

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Container Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to  GitHub Container Repository
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}


    - name: Build and push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: theonestack/cfhighlander:${{ github.event.release.tag_name }},theonestack/cfhighlander:latest
